//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelexBarDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminMsg
    {
        public System.Guid ID { get; set; }
        public System.Guid Sender { get; set; }
        public string Content { get; set; }
        public int Type { get; set; }
        public int Status { get; set; }
        public int IsRead { get; set; }
        public int Result { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
    }
}
