//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelexBarDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int HeadID { get; set; }
        public Nullable<int> LV { get; set; }
        public Nullable<int> OrderID { get; set; }
        public string Family { get; set; }
        public string Title { get; set; }
        public string Keywords { get; set; }
        public string Description { get; set; }
        public Nullable<int> IsShow { get; set; }
        public string SrcDetail { get; set; }
        public string SrcList { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string EngLishName { get; set; }
    }
}
