//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelexBarDLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RelexBarEntities : DbContext
    {
        public RelexBarEntities()
            : base("name=RelexBarEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminUser> AdminUser { get; set; }
        public DbSet<AdsList> AdsList { get; set; }
        public DbSet<BankList> BankList { get; set; }
        public DbSet<Cart> Cart { get; set; }
        public DbSet<RecAddress> RecAddress { get; set; }
        public DbSet<Recharge> Recharge { get; set; }
        public DbSet<RedPacket> RedPacket { get; set; }
        public DbSet<RedPacketList> RedPacketList { get; set; }
        public DbSet<SysConfig> SysConfig { get; set; }
        public DbSet<TransferOut> TransferOut { get; set; }
        public DbSet<VerifyCodes> VerifyCodes { get; set; }
        public DbSet<Web_Area> Web_Area { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<vw_Orders> vw_Orders { get; set; }
        public DbSet<UserMsg> UserMsg { get; set; }
        public DbSet<Report> Report { get; set; }
        public DbSet<OtherPayServiceLog> OtherPayServiceLog { get; set; }
        public DbSet<Logs> Logs { get; set; }
        public DbSet<OrderList> OrderList { get; set; }
        public DbSet<RechargeCard> RechargeCard { get; set; }
        public DbSet<PayRecord> PayRecord { get; set; }
        public DbSet<PayListDetail> PayListDetail { get; set; }
        public DbSet<Holidays> Holidays { get; set; }
        public DbSet<UserHelp> UserHelp { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<AdminMenu> AdminMenu { get; set; }
        public DbSet<Shop> Shop { get; set; }
        public DbSet<TrueProduct> TrueProduct { get; set; }
        public DbSet<FavoritesProduct> FavoritesProduct { get; set; }
        public DbSet<AdminMsg> AdminMsg { get; set; }
        public DbSet<OrderProductList> OrderProductList { get; set; }
        public DbSet<ProductList> ProductList { get; set; }
        public DbSet<RecordsOfConsumption> RecordsOfConsumption { get; set; }
        public DbSet<PayList> PayList { get; set; }
        public DbSet<AdminRole> AdminRole { get; set; }
        public DbSet<AdminRoleMenu> AdminRoleMenu { get; set; }
    }
}
