//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelexBarDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderList
    {
        public System.Guid ID { get; set; }
        public string Number { get; set; }
        public Nullable<System.Guid> ShopID { get; set; }
        public Nullable<System.Guid> UID { get; set; }
        public string RecName { get; set; }
        public string RecAreaID { get; set; }
        public string RecAddress { get; set; }
        public string RecPhone { get; set; }
        public string RecAreaCode { get; set; }
        public string RecEmail { get; set; }
        public Nullable<int> RecSex { get; set; }
        public string Payment { get; set; }
        public string PayNumber { get; set; }
        public int PriceType { get; set; }
        public decimal Price { get; set; }
        public decimal Fee { get; set; }
        public Nullable<int> OrderType { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> PayTime { get; set; }
        public Nullable<System.DateTime> SendTime { get; set; }
        public Nullable<System.DateTime> RecTime { get; set; }
        public Nullable<System.DateTime> FinishTime { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<System.Guid> RecID { get; set; }
        public string Notes { get; set; }
        public Nullable<decimal> LocalPrice { get; set; }
        public Nullable<decimal> OtherPrice { get; set; }
        public Nullable<decimal> Cash { get; set; }
    }
}
