//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelexBarDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductList
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ShopID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Number { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Img { get; set; }
        public string ImgList { get; set; }
        public string Descrition { get; set; }
        public decimal RealPrice { get; set; }
        public int PriceType { get; set; }
        public decimal Price { get; set; }
        public decimal Stock { get; set; }
        public int OrderID { get; set; }
        public int Type { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public int Level { get; set; }
        public decimal DailySalary { get; set; }
        public int Payed { get; set; }
        public decimal CashDiscount { get; set; }
    }
}
