//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelexBarDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecAddress
    {
        public System.Guid ID { get; set; }
        public System.Guid UID { get; set; }
        public string TrueName { get; set; }
        public string AreaID { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string AreaCode { get; set; }
        public string Email { get; set; }
        public Nullable<int> Sex { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> IsDefault { get; set; }
    }
}
