//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelexBarDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shop
    {
        public System.Guid ID { get; set; }
        public string ShopName { get; set; }
        public System.Guid UID { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string Img { get; set; }
        public string AreaID { get; set; }
        public string Address { get; set; }
        public string BackImg { get; set; }
        public string IDcard_Img { get; set; }
        public string IDcard_Img2 { get; set; }
        public string BusinessLicense_Img { get; set; }
        public string ChatQQ { get; set; }
        public string ServicePhone { get; set; }
        public Nullable<int> AgentType { get; set; }
    }
}
