//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RelexBarDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrueProduct
    {
        public System.Guid SPID { get; set; }
        public System.Guid ProductID { get; set; }
        public string SPName { get; set; }
        public string SPDesc { get; set; }
        public string Number { get; set; }
        public decimal Weight { get; set; }
        public decimal RealPrice { get; set; }
        public int PriceType { get; set; }
        public decimal Price { get; set; }
        public decimal Stock { get; set; }
        public int Status { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string Remark { get; set; }
    }
}
